---
- name: Init Terraform
  shell: |
    cd {{ playbook_dir }}/../terraform/
    terraform init

- name: Running terraform apply for [IaC_Swarm]
  shell: |
    cd {{ playbook_dir }}/../terraform/
    terraform apply -auto-approve;

- name: Waiting for 15s to allow changes to propogate
  ansible.builtin.pause:
    seconds: 15