version: '3.8'

services:

  nginx:
    image: nginx:stable-alpine
    command: sh -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    environment:
      - ACTIVE_BACKEND=green-app
      - BACKUP_BACKEND=blue-app
    ports:
      - 80:80
    volumes:
      - /opt/default.template:/etc/nginx/conf.d/default.template
    deploy:
      replicas: 3
      placement:
        constraints: 
          - node.labels.type == manager
      update_config:
        parallelism: 1  #The number of containers to update at a time
        delay: 0s

  green-app:
    image: irishbandit/devblog:flask-v2
    hostname: "green-app-{{.Node.Hostname}}-{{.Task.ID}}"
    ports:
      - 8080
    environment:
      - DEPLOYMENT=GREEN
    command: python app.py
    deploy:
      replicas: 4
      placement:
        constraints: 
          - node.labels.deployment == green
          - node.labels.type != manager

  blue-app:
    image: irishbandit/devblog:flask-v2
    hostname: "blue-app-{{.Node.Hostname}}-{{.Task.ID}}"
    ports:
      - 8080
    environment:
      - DEPLOYMENT=BLUE
    command: python app.py
    deploy:
      replicas: 4
      placement:
        constraints: 
          - node.labels.deployment == blue
          - node.labels.type != manager