---
- name: Copying docker stack to master
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../docker/docker-stack.yml"
    dest: "/opt/"
    owner: ec2-user
    mode: '0777'

- name: Copying nginx template to remote
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../docker/loadbalancer/default.template"
    dest: "/opt/"
    owner: ec2-user
    mode: '0777'

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: swarm
    compose:
      - '/opt/docker-stack.yml'