---
- name: workers leave the swarm
  hosts: workers
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - leave-swarm

- name: managers leave the swarm
  hosts: manager
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - leave-swarm