---
- name: install packages
  hosts: docker_nodes
  become: yes
  roles: 
    - docker-installation

- name: create a new user account
  hosts: docker_nodes
  become: yes
  vars:
      users: 
        -  "{{ dev_user }}"
  roles: 
     - create-user

- name: initialize docker swarm
  hosts: managers[0]
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - swarm-init

- name: Add managers to the swarm
  hosts: managers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles: 
    - swarm-manager

- name: add workers to the swarm
  hosts: workers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - swarm-worker

- name: Add labels to each node in the swarm
  hosts: managers[0]
  become: yes
  roles:
    - add-swarm-labels

- name: Copy NGINX config to manager hosts
  hosts: managers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - copy-nginx

- name: Deploy docker stack for blue-green deployment 
  hosts: managers[0]
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - deploy-stack