---
- name: install pkgs & docker engine
  hosts: docker-nodes
  become: yes
  roles: 
    - docker-installation


- name: create a new user account
  hosts: docker-nodes
  become: yes
  vars:
      users: 
        -  "{{ dev_user }}"
  roles: 
     - create-user

- name: initialize docker swarm
  hosts: swarm-manager
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - swarm-init

- name: add workers to the swarm
  hosts: workers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - swarm-worker

- name: Add labels to each node in the swarm
  hosts: swarm-manager
  become: yes
  roles:
    - add-swarm-labels
