---
- name: Add labels to each node in the swarm
  hosts: swarm-manager
  become: yes
  roles:
    - add-swarm-labels

- name: Deploy docker stack for blue-green deployment 
  hosts: swarm-manager
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  roles:
    - deploy-stack