---
- name: Add Workers to the Swarm
  docker_swarm:
    state: join
    join_token: "{{ hostvars['swarm-manager-0']['worker_token']['stdout'] }}"
    remote_addrs: [ "{{ hostvars['swarm-manager-0']['ansible_default_ipv4']['address'] }}:2377" ]
  tags: swarm